server:
    port: 8080
    tomcat: 
        uri-encoding : UTF-8
        
logging:
    level:
        com.example: DEBUG

spring:
    application.name : DEMO
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;charaterEncoding=utf-8
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 10
        initialSize: 5
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxOpenPreparedStatements: 20
    http : 
        encoding :
            charset : UTF-8
            force : true

#mybatis.config : # mybatis config file
#mybatis.mapperLocations : # mappers file
#mybatis.typeAliasesPackage= # domain object's package 
#mybatis.typeHandlersPackage= # handler's package
#mybatis.check-config-location= # check the mybatis configuration exists
#mybatis.executorType : 